# ==================================================
# Web Server
# ==================================================

# 智能胰岛素泵仿真系统运行端口
server.port=9100


# ==================================================
# H2 Database
# ==================================================

# 使用本地文件数据库。
#
# 数据将保存在项目目录：
#
# data/insulin_pump_db.mv.db
#
# 因此关闭 Spring Boot 后，
# 历史记录不会消失。
spring.datasource.url=jdbc:h2:file:./data/insulin_pump_db

# H2 数据库驱动
spring.datasource.driver-class-name=org.h2.Driver

# 本地课程仿真数据库用户名
spring.datasource.username=sa

# 本地数据库暂不设置密码
spring.datasource.password=


# ==================================================
# JPA / Hibernate
# ==================================================

# 自动根据 Java Entity 创建或更新数据库表。
#
# update：
# 如果表不存在则创建；
# 如果已经存在则保留数据并更新结构。
spring.jpa.hibernate.ddl-auto=update

# 在 CMD 中显示执行的 SQL。
# 方便开发阶段观察数据库操作。
spring.jpa.show-sql=true


# ==================================================
# H2 Console
# ==================================================

# 开启 H2 自带数据库管理网页。
spring.h2.console.enabled=true

# H2 管理页面访问地址：
#
# http://localhost:9100/h2-console
spring.h2.console.path=/h2-console

# DeepSeek 仅用于 AI Agent 的文字解释，不参与 Dose 或 Pump 控制。
deepseek.api-url=https://api.deepseek.com/chat/completions
deepseek.model=deepseek-chat
